version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:14.15.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "functions/package-lock.json" }}
          - v1-dependencies-

      - run: cd functions && npm install

      - run:
          name: 'Install firebase-tools'
          command: npm install

      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-{{ checksum "functions/package-lock.json" }}

      - run:
          name: 'set .firebaserc'
          command: echo -e "{\n  {\n    \"projects\": {\n        \"default\": \"$FIREBASE_PJ\"\n  }\n}\n" > .firebaserc

      - run:
          name: 'Deploy to Firebase'
          command: node_modules/.bin/firebase deploy --only functions --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
